services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SSL_KEY_PASSWORD: ${SSL_KEY_PASSWORD}
      SERVER_DOMAIN: ${SERVER_DOMAIN}

    ports:
      - "8443:8443"

    volumes:
      - ./logs:/var/logs

    depends_on:
      - db

  ###

  db:
    image: postgres

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

  ###

  test:
    build:
      context: .
      dockerfile: Dockerfile.test

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SSL_KEY_PASSWORD: ${SSL_KEY_PASSWORD}
      SERVER_DOMAIN: ${SERVER_DOMAIN}

    volumes:
      - ./reports:/app/build/reports

    depends_on:
      - db-test

  ###

  db-test:
    image: postgres

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres_data:
