services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app

    environment:
      DB_HOST: app-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SSL_KEY_PASSWORD: ${SSL_KEY_PASSWORD}
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      IMAGE_QUALITY: ${IMAGE_QUALITY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}

    ports:
      - "8443:8443"

    volumes:
      - ./logs:/var/logs

    depends_on:
      - app-db

    networks:
      - app-network

  ###

  app-db:
    image: postgres

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app-network

  ###
  ###
  ###
  ###
  ###

  test:
    build:
      context: .
      dockerfile: Dockerfile.test

    environment:
      DB_HOST: test-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SSL_KEY_PASSWORD: ${SSL_KEY_PASSWORD}
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      IMAGE_QUALITY: ${IMAGE_QUALITY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}

    volumes:
      - ./reports:/app/build/reports

    depends_on:
      - test-db

    networks:
      - test-network

  ###

  test-db:
    image: postgres

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    networks:
      - test-network

    tmpfs:
      - /var/lib/postgresql/data

###
###
###
###
###

volumes:
  postgres_data:

networks:
  app-network:
  test-network:
