app:
  image:
    quality: ${IMAGE_QUALITY}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  web:
    resources:
      add-mappings: false

  jpa:
    show-sql: false
    open-in-view: false

    hibernate:
      ddl-auto: create-drop

logging:
  file:
    path: /var/logs/
  level:
    root: WARN
    "[ru.nskopt]": INFO

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: ${JWT_EXPIRATION_TIME}

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type:
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY_PASSWORD}
    key-alias: server
